name: Build & Release

on:
  push:
    branches: []
    tags:
      - 'v*'
      - "testing"
    paths:
      - 'src/**'
      - '.github/**'

jobs:
  build-and-release:
    # TODO: Move to macos-11.0 when it's out of private preview
    #       https://github.com/actions/virtual-environments/issues/2486
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Flakes don't work on shallow clones
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210207_fd6eaa1/install

      - name: Enable Flakes
        run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf

      - name: Build
        id: build-bin
        run: |
          make all

      - name: Check execution & get version
        id: check-bin
        run: |
          echo "::set-output name=version::$(./bin/spacebar --version | cut -d- -f2)"

      - name: Build with Nix
        run: |
          nix build

      - name: Get the current tag name
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Check bin version before release
        if: ${{ startsWith(github.ref, 'refs/tags/') && !startsWith(github.ref, 'refs/tags/testing') }}
        run: |
          [[ "$RELEASE_VERSION" == ${{ steps.check-bin.outputs.version }} ]]

      - name: Create release archive
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: archive
        run: |
          tar czvf spacebar-$RELEASE_VERSION.tar.gz bin/spacebar doc examples
          echo "::set-output name=file::spacebar-$RELEASE_VERSION.tar.gz"
          echo "::set-output name=sha::$(shasum -a 256 spacebar-$RELEASE_VERSION.tar.gz | cut -d" " -f1)"

      - name: Create release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: ${{ startsWith(github.ref, 'refs/tags/testing') }}
          tag_name: ${{ github.ref }}
          release_name: ${{ env.RELEASE_VERSION }}
          body: |
            [Changelog](https://github.com/cmacrae/spacebar/blob/master/CHANGELOG.md)

            You can find a precompiled release tarball in the release assets below.  
            SHA-256 checksum:  
            `${{ steps.archive.outputs.sha }}`

      - name: Upload release archive
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ steps.archive.outputs.file }}
          asset_name: ${{ steps.archive.outputs.file }}
          asset_content_type: application/gzip
